# Generated by Django 3.0.6 on 2022-03-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id_supplier', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('supplier_tax_code', models.CharField(max_length=100)),
                ('city_id', models.CharField(max_length=10)),
                ('city_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('nit', models.CharField(max_length=20)),
                ('supplier_tax_description', models.CharField(max_length=70)),
                ('Type_of_tax_number', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=10)),
                ('est_fed_prov', models.CharField(max_length=10)),
                ('name_est_fed_prov', models.CharField(max_length=40)),
                ('currency_type', models.CharField(max_length=10)),
            ],
        ),
    ]
