# Generated by Django 3.0.6 on 2022-04-04 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocSupApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='date_Invoice',
            field=models.DateField(verbose_name=datetime.date),
        ),
    ]
