# Generated by Django 3.0.6 on 2022-03-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocSupApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='det_fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_supplier', models.CharField(max_length=10)),
                ('name_supplier', models.CharField(max_length=70)),
                ('id_supplier_invoice', models.CharField(max_length=50)),
                ('date_Invoice', models.DateTimeField()),
                ('zPaymentMethod', models.CharField(max_length=40)),
                ('idItem', models.CharField(max_length=10)),
                ('item_description', models.CharField(max_length=100)),
                ('zSupplierName', models.CharField(max_length=50)),
                ('zSupplierID', models.CharField(max_length=10)),
                ('Business_transaction_document_id', models.CharField(max_length=30)),
                ('net_amount', models.CharField(max_length=20)),
                ('tax_amount', models.CharField(max_length=20)),
                ('gross_amount', models.CharField(max_length=20)),
                ('percent_RTE', models.CharField(max_length=20)),
                ('percent_IVA', models.CharField(max_length=20)),
                ('percent_ICA', models.CharField(max_length=20)),
                ('amount_RTE', models.CharField(max_length=20)),
                ('amount_IVA', models.CharField(max_length=20)),
                ('amount_ICA', models.CharField(max_length=20)),
                ('Value_RTE', models.CharField(max_length=20)),
                ('total_retenciones', models.CharField(max_length=20)),
            ],
        ),
    ]
