# Generated by Django 3.0.6 on 2022-03-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocSupApp', '0002_det_fact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='det_fact',
            name='zSupplierName',
            field=models.CharField(max_length=100),
        ),
    ]
