# Generated by Django 3.0.6 on 2022-04-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocSupApp', '0002_auto_20220404_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='status',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
