# Generated by Django 3.0.6 on 2022-04-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocSupApp', '0003_auto_20220406_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='payment_date',
            field=models.DateField(null=True),
        ),
    ]
