# Generated by Django 3.0.6 on 2022-03-31 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocSupApp', '0003_auto_20220331_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='det_fact',
            name='name_supplier',
            field=models.CharField(max_length=80),
        ),
    ]
