# Generated by Django 3.0.6 on 2022-04-14 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocSupApp', '0004_documento_payment_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='documento',
        ),
        migrations.DeleteModel(
            name='proveedor',
        ),
    ]
