# Generated by Django 3.0.6 on 2022-04-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocSupApp', '0004_auto_20220331_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='det_fact',
            name='id',
        ),
        migrations.AlterField(
            model_name='det_fact',
            name='id_supplier',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
