# Generated by Django 3.0.6 on 2022-04-01 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocSupApp', '0005_auto_20220331_1908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='det_fact',
        ),
    ]
