# Generated by Django 3.0.6 on 2022-04-14 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DocSupApp', '0005_auto_20220414_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='documento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_supplier_vendor', models.CharField(max_length=20)),
                ('name_supplier_vendor', models.CharField(max_length=100)),
                ('suplier_tax_code', models.CharField(max_length=10)),
                ('city_id', models.CharField(max_length=10)),
                ('city_name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('Nit', models.CharField(max_length=20)),
                ('type_of_tax_number', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=10)),
                ('est_fed_prov', models.CharField(max_length=10)),
                ('name_est_fed_prov', models.CharField(max_length=40)),
                ('currency_type', models.CharField(max_length=20)),
                ('supplier_id_Customer', models.CharField(max_length=20)),
                ('name_supplier_customer', models.CharField(max_length=100)),
                ('id_supplier_invoice', models.CharField(max_length=55)),
                ('date_Invoice', models.DateField(verbose_name=datetime.date)),
                ('idItem', models.CharField(max_length=40)),
                ('item_description', models.CharField(max_length=100)),
                ('zSupplierID', models.CharField(max_length=20)),
                ('zSupplierName', models.CharField(max_length=100)),
                ('net_amount', models.CharField(max_length=20)),
                ('tax_amount', models.CharField(max_length=20)),
                ('gross_amount', models.CharField(max_length=20)),
                ('percent_RTE', models.CharField(max_length=20)),
                ('percent_IVA', models.CharField(max_length=20)),
                ('percent_ICA', models.CharField(max_length=20)),
                ('amount_RTE', models.CharField(max_length=20)),
                ('amount_IVA', models.CharField(max_length=20)),
                ('amount_ICA', models.CharField(max_length=20)),
                ('Value_RTE', models.CharField(max_length=30)),
                ('total_retenciones', models.CharField(max_length=30)),
                ('tipo_persona', models.IntegerField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('Date_process', models.DateTimeField(null=True)),
                ('user_process', models.CharField(max_length=30, null=True)),
                ('payment_date', models.DateField(null=True)),
                ('num_documento', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='properties',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Num_resolution', models.IntegerField()),
                ('path_file', models.CharField(max_length=100, null=True)),
                ('name_file', models.CharField(max_length=100, null=True)),
                ('autorization', models.CharField(max_length=100, null=True)),
                ('start_date_res', models.DateField(null=True)),
                ('end_date_res', models.DateField(null=True)),
                ('prefijo_res', models.CharField(max_length=10, null=True)),
                ('initial_range_res', models.IntegerField(null=True)),
                ('end_range_res', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id_supplier', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('supplier_tax_code', models.CharField(max_length=10)),
                ('city_id', models.CharField(max_length=10)),
                ('city_name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('nit', models.CharField(max_length=20)),
                ('supplier_tax_description', models.CharField(max_length=70)),
                ('Type_of_tax_number', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=10)),
                ('est_fed_prov', models.CharField(max_length=10)),
                ('name_est_fed_prov', models.CharField(max_length=40)),
                ('currency_type', models.CharField(max_length=10)),
            ],
        ),
    ]
