# Generated by Django 3.0.6 on 2022-04-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocSupApp', '0006_delete_det_fact'),
    ]

    operations = [
        migrations.CreateModel(
            name='detalle_fact_2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_id', models.CharField(max_length=10)),
                ('name_supplier', models.CharField(max_length=70)),
                ('id_supplier_invoice', models.CharField(max_length=50)),
                ('date_Invoice', models.DateTimeField()),
                ('zPaymentMethod', models.CharField(max_length=40)),
                ('idItem', models.CharField(max_length=10)),
                ('item_description', models.CharField(max_length=100)),
                ('zSupplierName', models.CharField(max_length=50)),
                ('zSupplierID', models.CharField(max_length=10)),
                ('Business_transaction_document_id', models.CharField(max_length=30)),
                ('net_amount', models.CharField(max_length=20)),
                ('tax_amount', models.CharField(max_length=20)),
                ('gross_amount', models.CharField(max_length=20)),
                ('percent_RTE', models.CharField(max_length=20)),
                ('percent_IVA', models.CharField(max_length=20)),
                ('percent_ICA', models.CharField(max_length=20)),
                ('amount_RTE', models.CharField(max_length=20)),
                ('amount_IVA', models.CharField(max_length=20)),
                ('amount_ICA', models.CharField(max_length=20)),
                ('Value_RTE', models.CharField(max_length=20)),
                ('total_retenciones', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=0, null=True)),
                ('Date_process', models.DateTimeField(null=True)),
                ('user_process', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
