# Generated by Django 3.0.6 on 2022-04-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocSupApp', '0006_documento_properties_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo_persona',
            field=models.TextField(choices=[('1', 'Persona Natural'), ('13', 'Persona Juridica')], null=True),
        ),
    ]
