# Generated by Django 3.0.6 on 2022-04-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocSupApp', '0007_auto_20220414_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='status',
            field=models.TextField(null=True),
        ),
    ]
