# Generated by Django 3.0.6 on 2022-04-01 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocSupApp', '0008_auto_20220331_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_fact_2',
            name='Business_transaction_document_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='detalle_fact_2',
            name='Value_RTE',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='detalle_fact_2',
            name='amount_ICA',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='detalle_fact_2',
            name='idItem',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='detalle_fact_2',
            name='id_supplier_invoice',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='detalle_fact_2',
            name='total_retenciones',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='detalle_fact_2',
            name='zPaymentMethod',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='detalle_fact_2',
            name='zSupplierID',
            field=models.CharField(max_length=20),
        ),
    ]
