# Generated by Django 3.0.6 on 2022-04-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocSupApp', '0008_auto_20220415_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo_persona',
            field=models.TextField(choices=[('2', 'Persona Natural'), ('1', 'Persona Juridica')], null=True),
        ),
    ]
