# Generated by Django 3.0.6 on 2022-07-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocSupApp', '0011_proveedor_dv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='dv',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
