# Generated by Django 3.0.6 on 2022-07-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocSupApp', '0012_auto_20220708_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='dv',
            field=models.IntegerField(null=True),
        ),
    ]
