# Generated by Django 3.0.6 on 2022-07-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocSupApp', '0013_auto_20220708_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='Motivo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='User_create_NC',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha_NC',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='genero_nota_credito',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='name_file_NC',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
