# Generated by Django 3.0.6 on 2022-07-14 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocSupApp', '0014_auto_20220714_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='Motivo',
            new_name='motivo',
        ),
    ]
