# Generated by Django 3.0.6 on 2022-07-14 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocSupApp', '0015_auto_20220714_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='User_create_NC',
            new_name='user_create_NC',
        ),
    ]
