# Generated by Django 3.0.6 on 2022-07-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocSupApp', '0016_auto_20220714_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='tasa_cambio',
            field=models.IntegerField(null=True),
        ),
    ]
