# Generated by Django 3.0.6 on 2022-07-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocSupApp', '0017_documento_tasa_cambio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tasa_cambio',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
