# Generated by Django 3.0.6 on 2022-07-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocSupApp', '0018_auto_20220725_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='fecha_tasa_cambio',
            field=models.DateField(null=True),
        ),
    ]
